on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 3"

jobs:
  autofix:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        target:
          - {repository: racket-actor, package: actor-lib}
          - {repository: racket-sentry, package: sentry-lib}
          - {repository: koyo-sentry, package: koyo-sentry}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Autofix package
        uses: ./.github/actions/autofix
        with:
          owner: Bogdanp
          repository: ${{ matrix.target.repository }}
          package: ${{ matrix.target.package }}
          private-key: ${{ secrets.RESYNTAX_APP_PRIVATE_KEY }}
